### ISSUE TITLE
It crashes when I go into any week other than tutorial.

### ISSUE THREAD

**Issue by TurtleFanCoder** [GuglioIsStupid/Funkin3D#1]
Nice port, Tutorial worked really really well and the engine runs great on an old 3ds. I couldn't get into any weeks other than Tutorial. When I ran any week other than tutorial I got a blue (top) screen with this text on it:

    Error

    states/weeks.lua:380: attempt to perform arithmetic on global 'bpm' (a nil value)

    Traceback

    [love "callbacks.lua"]:396: in function 'handler'
    states/weeks.lua:380: in function 'setupCountdown'
    states/weeks/week3.lua:76: in function 'initUI'
    states/weeks/week3.lua:63: in function 'load'
    states/weeks/week3.lua:47: in function 'enter'
    lib/state.lua:40: in function 'switch'
    lib/state.lua:47: in function 'switch'
    states/menu/storyMode.lua:61: in function 'after'
    lib/timer.lua:26: in function 'c'
    lib/timer.lua:26: in function <lib/timer.lua:26>
    (tail call): ?
    main.lua:176: in function 'update'
    [love "callbacks.lua"]:287: in function <[love "callbacks.lua"]:263>
    [C]: in function 'xpcall'
 
Am I doing something wrong or does it not work well on the Old 3DS?

**Comment by GuglioIsStupid** [comment]
> I personally can't test on o3ds, but this shouldn't be happening to begin with, because this would be a global issue

I'll look into it soon

**Comment by TurtleFanCoder** [comment]
Alright thanks

**Comment by ZGStuff** [comment]
same here, it crashes when I do anything other than tutorial :P

**Comment by TurtleFanCoder** [comment]
as of recent i got a new 3ds and it works there so

**Comment by GuglioIsStupid** [comment]
I think for the last update to this version, I'll fix the weeks not working (and maybe even add week6, week6 may be a bit too much rn)

I'm trying to port it over to CPP, but having issues with the sprites :P there's not really any great CPP libs

I think I'm gonna try optimizing notes for 3ds

**Comment by GuglioIsStupid** [comment]
Week6 may be a bit too much*

**Comment by GuglioIsStupid** [comment]
Why does it keep auto correcting week7 to week6.

**Comment by GuglioIsStupid** [comment]
Idk when I did fix it, but apparently I did long ago..,.,,. Ill make a new release
