### ISSUE TITLE
play week then the tutorial will cause crash

### ISSUE THREAD

**Issue by Trickiy** [GuglioIsStupid/Funkin3D#2]
I played Pico's week then tried to open the tutorial then this error.
![image](https://github.com/GuglioIsStupid/Funkin3D/assets/86691033/354fc468-9ad2-4a4f-9370-e986665677cd)

**Comment by GuglioIsStupid** [comment]
![image](https://github.com/GuglioIsStupid/Funkin3D/assets/96344386/9d96064c-511e-4dc6-a218-f24a1ab74d67)

**Comment by GuglioIsStupid** [comment]
Seems this is an older build and not up-to-date with the latest git source, so ill have to do some testing and see if it still exists (when i have time)
